"""initial

Revision ID: 8595a3a51bd4
Revises: 
Create Date: 2026-06-18 15:00:43.466144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8595a3a51bd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_job_id', sa.String(length=255), nullable=True),
    sa.Column('ocr_raw_text', sa.Text(), nullable=True),
    sa.Column('pages', sa.JSON(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('matched_rule_id', sa.String(length=50), nullable=True),
    sa.Column('matched_rule_name', sa.String(length=255), nullable=True),
    sa.Column('test_item', sa.String(length=500), nullable=True),
    sa.Column('sub_item', sa.String(length=500), nullable=True),
    sa.Column('recognized_value', sa.String(length=500), nullable=True),
    sa.Column('standard_requirement', sa.String(length=500), nullable=True),
    sa.Column('judgment', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('include_in_report', sa.Boolean(), nullable=False),
    sa.Column('sample_name', sa.String(length=255), nullable=True),
    sa.Column('entrust_no', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_filename'), 'photos', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_filename'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
